---
title: "sanity.test.usage"
author: "Jhonatan Casale"
date: "May 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
source("sanityCheck.R")
```

## Casos de uso para os casos em que a comparação de igualdade por valor absoluto (==) não era bem o que se queria.

### Para character vectors
```{r}
"a" %==% "a"
"this is a test" %==% "this is a test"
"not" %==% "equal"
```

### Para numeric vectors unitários
```{r}
1 %==% 1
2 %==% 1
4.5 %==% 4.5
1e-17 %==% 1.1e-17
```

### Para numeric vectors
```{r}
a <- 1:10 ; b <- 1:10
a %==% b

a[1] = 0
a %==% b

a <- (1:10) / 1e20 ; b <- (1:10) / 1e20
a %==% b

a <- (1:10) / 1e10 ; b <- (1:10) / 1e10
a %==% b
```


### Para numeric matrices
```{r}
a <- matrix(1:16, 4) ; b <- matrix(1:16, 4)
a %==% b

a <- matrix(2:17, 4) ; b <- matrix(1:16, 4)
a %==% b

a <- matrix(1:16 / 1e6, 4) ; b <- matrix(1:16 / 1e6, 4)
a %==% b

a <- matrix(2:17 / 1e9, 4) ; b <- matrix(1:16 / 1e9, 4)
a %==% b
a
b
sum((a - b) ^ 2)
```

