---
title: "Loop Structures"
output:
  html_notebook: default
  pdf_document: default
---

## For loop

```{r}
#for (<iterator>) {
#  ## do something
#}
```

```{r}
for(i in 1:10) {
  print(i)
}
```
```{r}
x <- c("a", "b", "c", "d")
```

```{r}
for(i in 1:4) { ## or for (i in 1:length(x)) {
  print(x[i])
}
```

```{r}
for(i in seq_along(x)) {
  print(x[i])  
}
```

```{r}
for(letter in x) { 
  print(letter)
}
```

```{r}
for(letter in x) print(letter)
```

```{r}
for(i in 1:4) print(x[i])
```

```{r}
x <- matrix(1:6, 2, 3)

for(i in seq_len(nrow(x))) {
  for (j in seq_len(ncol(x))) {
    print(x[i, j])
  }  
}
x
```

## While loop

```{r}
count <- 0
while(count < 10) {
  print(count)
  count <- count + 1
}
```

```{r}
z <- 5

while(z >= 3 && z <= 10) {
  print(z)
  
  coin <- rbinom(1, 1, .5)
  
  if(coin == 1) {
    z <- z + 1
  } else {
    z <- z - 1
  }
}
```

```{r}
z <- 5
times <- 0

while(z >= 3 && z <= 10) {
  print(z)
  
  coin <- rbinom(1, 1, .5)
  
  ## random walk
  z <- z + if(coin == 1) 1 else -1
  times <- times + 1
}
times
```

## Repeat loop
```{r}
repeat {
  ## do something
  ## at some point
  break
}  
```

## Next
```{r}
for(i in 1:100) {
  if(i <= 20) {
    ## skip the first 20 iterations
    next
  }
  # do something
}
```


